export const Constant: any = {
  AUTH : "/api/v1/auth/authenticate",
  REGISTER_CLIENT: "/api/v1/client",
  REGISTER_LAWYER: "/api/v1/lawyer",
  CITY: "/api/v1/city",
  CHAT_AI: "/api/v1/chatbot?userInput=",
  UPDATE_ABOUT_ME: "/api/v1/lawyer/updateAboutMe/",
  UPDATE_LAWYER_CARD_PHOTO: "/api/v1/lawyer/addAvukatKartPhoto/",
  UPDATE_TC_PHOTO: "/api/v1/lawyer/addTcPhoto/",
  UPDATE_LAWYER_PHOTO: "/api/v1/lawyer/addLawyerPhoto/",
  GET_LAWYER: "/api/v1/lawyer/",
  GET_ALL_LAWYER: "/api/v1/lawyer/",
  UPDATE_SOCIAL_CONTACT_INFO: "/api/v1/lawyer/updateSocialContact",
  GET_EXPERTISE_FIELDS: "/api/v1/expertisefield",
  ADD_EXPERTISE_FIELD: "/api/v1/lawyer/addExpertiseField",
  REMOVE_EXPERTISE_FIELD: "/api/v1/lawyer/removeExpertiseField",
  CREATE_COMMON_QUESTION: "/api/v1/commonquestion",
  DELETE_COMMON_QUESTION: "/api/v1/commonquestion/",
  CREATE_ADDRESS : "/api/v1/address",
  CREATE_POST : "/api/v1/post",
  ADD_POST_PHOTO : "/api/v1/post/addPostPhoto/",
  GET_ALL_POSTS:"/api/v1/post/",
  CREATE_LIKE: "/api/v1/like",
  DELETE_LIKE: "/api/v1/like/",
  CREATE_ARTICLE: "/api/v1/article",
  DELETE_ARTICLE: "/api/v1/article/",
  ADD_ARTICLE_PHOTO: "/api/v1/article/"
}
