export const Constant: any = {
  AUTH : "/api/v1/auth/authenticate",
  REGISTER_CLIENT: "/api/v1/client",
  REGISTER_LAWYER: "/api/v1/lawyer",
  CITY: "/api/v1/city",
  CHAT_AI: "/api/v1/chatbot?userInput=",
  UPDATE_ABOUT_ME: "/api/v1/lawyer/updateAboutMe/",
  UPDATE_LAWYER_CARD_PHOTO: "/api/v1/lawyer/addAvukatKartPhoto/",
  UPDATE_TC_PHOTO: "/api/v1/lawyer/addTcPhoto/",
  UPDATE_LAWYER_PHOTO: "/api/v1/lawyer/addLawyerPhoto/",
  GET_LAWYER: "/api/v1/lawyer/",
  GET_ALL_LAWYER: "/api/v1/lawyer/",
  UPDATE_SOCIAL_CONTACT_INFO: "/api/v1/lawyer/updateSocialContact",
  GET_EXPERTISE_FIELDS: "/api/v1/expertisefield",
  ADD_EXPERTISE_FIELD: "/api/v1/lawyer/addExpertiseField",
  REMOVE_EXPERTISE_FIELD: "/api/v1/lawyer/removeExpertiseField",
}
